CREATE TABLE IF NOT EXISTS Wishlists (
    wishlistId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userId INT NOT NULL,
    wishlistName VARCHAR(255) NOT NULL,
    wishlistDescription TEXT,
    createDate TIMESTAMP NOT NULL,
    modifiedDate TIMESTAMP NOT NULL,
    CONSTRAINT fk_wishlist_user FOREIGN KEY (userId) REFERENCES Users(userId) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS WishlistItems (
    wishlistId INT NOT NULL,
    itemId INT NOT NULL,
    PRIMARY KEY (wishlistId, itemId),
    CONSTRAINT fk_wishlistitems_wishlist FOREIGN KEY (wishlistId) REFERENCES Wishlists(wishlistId) ON DELETE CASCADE,
    CONSTRAINT fk_wishlistitems_item FOREIGN KEY (itemId) REFERENCES Items(itemId) ON DELETE CASCADE
);