CREATE TABLE IF NOT EXISTS parsing_tasks (
    task_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url VARCHAR(500) NOT NULL,
    user_id INT NOT NULL,
    wishlist_id INT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PROCESSING',
    error_message TEXT NULL,
    created_item_id INT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Внешние ключи
    CONSTRAINT fk_parsing_tasks_user
        FOREIGN KEY (user_id) REFERENCES Users(userId) ON DELETE CASCADE,

    CONSTRAINT fk_parsing_tasks_wishlist
        FOREIGN KEY (wishlist_id) REFERENCES Wishlists(wishlistId) ON DELETE SET NULL,

    CONSTRAINT fk_parsing_tasks_item
        FOREIGN KEY (created_item_id) REFERENCES Items(itemId) ON DELETE SET NULL,

    -- Проверка статуса
    CONSTRAINT chk_parsing_tasks_status
        CHECK (status IN ('PROCESSING', 'COMPLETED', 'FAILED'))
);